package ru.nsu.ccfit.izhitsky.GUI;

import ru.nsu.ccfit.izhitsky.Client.MyClient;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class GUIIntro
{
	private JPanel mainPanel;
	private JRadioButton javaObjectsRadioButton;
	private JRadioButton XMLRadioButton;
	private JTextField serverIPTextField;
	private JTextField serverPortTextField;
	private JButton LAUNCHCLIENTButton;
	private JButton EXITButton;
	private int port;
	private String IP;
	private MyClient.TYPE type;
	private MyClient theClient;

	public GUIIntro()
	{
		JFrame theFrame = new JFrame("Chat Client Intro Window");
		theFrame.setContentPane(mainPanel);
		theFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		theFrame.pack();
		theFrame.setVisible(true);
		type = MyClient.TYPE.OS;

		LAUNCHCLIENTButton.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent actionEvent)
			{
				IP = serverIPTextField.getText();
				boolean b1_0 = IP.toLowerCase().equals("localhost");
				boolean b1_1 = IP.matches("((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)");
				boolean b1 = b1_0 || b1_1; //valid IP

				boolean b2 = true;
				try
				{
					port = Integer.parseInt(serverPortTextField.getText());
					if (port < 1024 || port > 49151)
					{
						b2 = false;
					}
				} catch (NumberFormatException e)
				{
					b2 = false;
				}

				if (b1 && b2)
				{
					theClient = new MyClient(IP, port, type);
					theClient.setConnectionListener(new MyClient.ConnectionListener()
					{
						@Override
						public void handle(boolean connected)
						{
							if (connected)
							{
								new GUIClient(theClient);
								theFrame.dispose();
							}
							else
							{
								JOptionPane.showMessageDialog(mainPanel, "Cannot connect to the server");
							}
						}
					});

					Thread connectionThread = new Thread(new LocalRunnable(), "Connection thread");
					connectionThread.start();
				}
				else
				{
					if (!b1 && !b2)
					{
						JOptionPane.showMessageDialog(mainPanel, "Invalid IP and port");
					}
					else if (!b1)
					{
						JOptionPane.showMessageDialog(mainPanel, "Invalid IP");
					}
					else //!b2
					{
						JOptionPane.showMessageDialog(mainPanel, "Invalid port");
					}
				}
			}
		});

		javaObjectsRadioButton.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent actionEvent)
			{
				type = MyClient.TYPE.OS;
			}
		});

		XMLRadioButton.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent actionEvent)
			{
				type = MyClient.TYPE.XML;
			}
		});

		EXITButton.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent actionEvent)
			{
				theFrame.dispose();
				System.exit(0);
			}
		});
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		mainPanel = new JPanel();
		mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
		javaObjectsRadioButton = new JRadioButton();
		javaObjectsRadioButton.setSelected(true);
		javaObjectsRadioButton.setText("Java Objects");
		mainPanel.add(javaObjectsRadioButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JLabel label1 = new JLabel();
		label1.setText("Server port");
		mainPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		serverIPTextField = new JTextField();
		serverIPTextField.setText("localhost");
		mainPanel.add(serverIPTextField, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		serverPortTextField = new JTextField();
		mainPanel.add(serverPortTextField, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		XMLRadioButton = new JRadioButton();
		XMLRadioButton.setSelected(false);
		XMLRadioButton.setText("XML");
		mainPanel.add(XMLRadioButton, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		LAUNCHCLIENTButton = new JButton();
		LAUNCHCLIENTButton.setBackground(new Color(-16760576));
		LAUNCHCLIENTButton.setForeground(new Color(-1));
		LAUNCHCLIENTButton.setText("LAUNCH CLIENT");
		mainPanel.add(LAUNCHCLIENTButton, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		EXITButton = new JButton();
		EXITButton.setBackground(new Color(-12517376));
		EXITButton.setForeground(new Color(-1));
		EXITButton.setText("EXIT");
		mainPanel.add(EXITButton, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JLabel label2 = new JLabel();
		label2.setText("use only 1024..49151");
		mainPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JLabel label3 = new JLabel();
		label3.setText("IPv4 only");
		mainPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JLabel label4 = new JLabel();
		label4.setText("Server");
		mainPanel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		ButtonGroup buttonGroup;
		buttonGroup = new ButtonGroup();
		buttonGroup.add(javaObjectsRadioButton);
		buttonGroup.add(XMLRadioButton);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return mainPanel;
	}

	//------------------------------------------------------------------------------------

	private class LocalRunnable implements Runnable
	{
		@Override
		public void run()
		{
			theClient.connectToServer();
		}
	}
}
